name: Analysis
on:
  pull_request: {}
  push:
    branches: [develop, main]
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: pnpm cache
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: "pnpm install --frozen-lockfile --ignore-scripts"
      - name: Lint
        run: "pnpm lint"
      - name: Check formatting
        run: "pnpm prettier:check"
  test:
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: pnpm cache
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: "pnpm install --frozen-lockfile --ignore-scripts"
      - name: Test
        run: "pnpm test --coverage"
      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage
          path: |
            coverage
            !coverage/lcov-report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  e2e:
    name: "Test end-to-end"
    # This must be kept in sync with the version of ubuntu used in the Docker
    # image, in playwright/Dockerfile
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: pnpm cache
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: "pnpm install --frozen-lockfile --ignore-scripts"
      - name: Build Storybook
        run: pnpm build-storybook
      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --depth=0 --json | jq -r '.[0].devDependencies["@playwright/test"].version')" >> $GITHUB_ENV
      - name: Cache Playwright binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright binaries
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        # We use this action to get a virtual frame buffer for the browsers
        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1
        with:
          run: pnpm playwright test -j 100%
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
