name: Visual Regression
on:
    pull_request: {}
    push:
        branches: [develop, main]

jobs:
    visual:
        name: "Percy"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"
            - name: Percy
              run: yarn && yarn percy:ci
